### ISSUE TITLE
Minor typo in log message

### ISSUE THREAD

**Issue by varenius** [jive-vlbi/etransfer#22]
When running etc (from issue-18) branch with message level 5 (-m 5) I get lines like
```
2022-02-08 08:25:47.96: [virtual etdc::xfer_result etdc::ETDServer::sendFile(const etdc::uuid_type&, const etdc::uuid_type&, off_t, const dataaddrlist_type&)] sendFile: ... got it
finished; succesfully transferred 2 GiB (1,971,202,336 bytes) in 37.61 s [49.99 MBps]
```
This is a really minor thing, but shouldn't there be an extra **s** in succesfully, i.e. "successfully" ? :)

**Comment by haavee** [comment]
And is fixed in commit 4db806efcdb9ecac96cbf20b9c28c087253ae317 which erroneously labelled it as closing issue #19 where it was this one.
