### ISSUE TITLE
Upon unforeseen client termination (e.g. kill -9), server does not release file lock

### ISSUE THREAD

**Issue by varenius** [jive-vlbi/etransfer#4]
As noted in #3, there are cases where the client may be forcefully terminated. This may not only be done by request, there could be other cases when the client is forcefully killed such as power outage. In these cases, we want the server to realise the client is gone and somehow release the grip on the file in question so that it can be resumed later.

With the current behaviour, when using the cleint to resume a transfer after termination, this error happens on the client side:
```
terminate called after throwing an instance of 'etdc::assertion_error'
  what():  assertion error: src/etdc_etdserver.cc:716 [status_s=="OK"] requestFileWrite(/gpfs/cdata/incoming/ow/vo1074_ow_074-1806a_0) failed - assertion error: src/etdc_etdserver.cc:159 [pathPresent==false] requestFileWrite(/gpfs/cdata/incoming/ow/vo1074_ow_074-1806a_0) - the path is already in use
Aborted
```
This can be remedied by restarting the server (etd). However, this means that effectively, due to the lack of handling CTRL-C (which may be needed to terminate the local client), then any resume operation later requires a server restart. This is not intended behaviour. 

Note: transferring other files, except for the one which is still "open" in the server side, does work without a server restart. So the server lives, it just fails to release the grip on the file being transferred when the client is killed.

**Comment by haavee** [comment]
This is dependent on the client gracefully handling ^C; once it did that this issue went away.

**Comment by varenius** [comment]
Great that ^C is handled properly. However, as I wrote in this ticket, there may be other cases such as power outages for when this happens. Therefore, this issue does not go away with the ^C handling fixed :). But, I acknowledge that the cases with power outages etc will be few.

What I think would be required, to properly fix this, is some timeout where the server (etd) could figure out that the client (etc) has dropped the connection, and then release any locks in place from this client. Timeout could be long (5 minutes or something). Just to avoid havin to restart the server (which may not be under the client-person's control).

**Comment by haavee** [comment]
When I said "^C" is handled I should have said that also `SIGTERM` and `SIGHUP` and `SIGSEGV` are handled in the same fashion. This would add "proper shutdown of the machine if it's on UPS" to the cases caught.
But yeah, immediate shutdown of the machine (or network) is still unhandled so will have to think a bit about e.g. a timeout at the server side indeed.
